spring:
  application:
    name: basilisk
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6000/basilisk
    username: postgres
    password: postgres


